import './data.alpine';
import './modules/analytics';
import './modules/slider';
import './modules/dropzone';
import './modules/scroll';
import './modules/map';
import './modules/form';
import './modules/modals';
import './modules/quiz';
// import './modules/btn.up';