import './data.alpine';
// import './modules/analytics';
import './modules/slider';
import './modules/dropzone';
// import './modules/map';
import './modules/scroll';
// import './modules/functions';
// import './modules/color.links';
// import './modules/map';
import './modules/form';
import './modules/modals';
// import './modules/btn.up';