name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issues:
    branches:
      - main
permissions:
  contents: write
jobs:
  build_and_deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Install, build, and upload your site output
        uses: withastro/action@v1
        with:
          package-manager: pnpm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)
          # path: . # The root location of your Astro project inside the repository. (optional)
          # node-version: 18 # The specific version of Node that should be used to build your site. Defaults to 18. (optional)

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm run build_on_deploy

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.

  notify_telegram:
    needs: build_and_deploy
    uses: ./.github/workflows/github-telegram.yml
    with:
      additional-text: 'After deploy'
    secrets:
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
